In [1]:
import numpy as np

In [3]:
x=np.array(6)  #scalar (0-D tensor)
print("x:", x)
print("x ndim:", x.ndim)
print("x shape:", x.shape)
print("x size:", x.size)
print("x dtype:", x.dtype)

x: 6
x ndim: 0
x shape: ()
x size: 1
x dtype: int64


In [4]:
x=np.array([1,2,3])  #Vector (1-D Tensor)
print("x:", x)
print("x ndim:", x.ndim)
print("x shape:", x.shape)   # 3 elements in ONE dimension. This is not a column or row yet (important!)
print("x size:", x.size)
print("x dtype:", x.dtype)

x: [1 2 3]
x ndim: 1
x shape: (3,)
x size: 3
x dtype: int64


In [5]:
x=np.array([[2,3],[4,5]])    # Matrix(2-D Tensor)
print("x:\n", x)
print("x ndim:", x.ndim)
print("x shape:", x.shape)    #2 rows × 2 columns
print("x size:", x.size)
print("x dtype:", x.dtype)

x:
 [[2 3]
 [4 5]]
x ndim: 2
x shape: (2, 2)
x size: 4
x dtype: int64


In [6]:
x=np.array([[[1,2],[3,5]],[[6,7],[8,9]]])
print("x:\n", x)
print("x ndim:", x.ndim)
print("x shape:", x.shape)   #2 blocks, 2 rows, 2 columns
print("x size:", x.size)
print("x dtype:", x.dtype)

x:
 [[[1 2]
  [3 5]]

 [[6 7]
  [8 9]]]
x ndim: 3
x shape: (2, 2, 2)
x size: 8
x dtype: int64


In [7]:
#Tensor Creation Functions (NumPy)
x=np.zeros((2,3))    #np.zeros()
print(x)
print("shape:", x.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
shape: (2, 3)


In [8]:
x=np.ones((3,2))    #np.ones()
print(x)
print("shape:", x.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
shape: (3, 2)


In [13]:
x=np.eye(3)    #np.eye()
print(x)
print("shape:", x.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
shape: (3, 3)


In [14]:
x=np.random.random((2,3))    #np.random.random()
print(x)
print("shape:", x.shape)

[[0.88442535 0.74527828 0.15678649]
 [0.2478855  0.45241108 0.51430545]]
shape: (2, 3)


In [15]:
# Indexing & Slicing (Data Selection in ML)
x = np.array([10, 20, 30])   #Basic Indexing (1D Array)
print("x:", x)
print("x[0]:", x[0])

x[0] = 0
print("after change:", x)

x: [10 20 30]
x[0]: 10
after change: [ 0 20 30]
